### ISSUE TITLE
Design details - old layout

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#33]
* [ ] visited links on "about" page are white text on white background. https://github.com/theblacksea/issues/issues/17
* [ ] mobile site - some text too small, missing links: https://github.com/theblacksea/issues/issues/10 https://github.com/theblacksea/issues/issues/9
* [ ] social icons on homepage https://github.com/theblacksea/issues/issues/8
