### ISSUE TITLE
Manual content cleanup

### ISSUE THREAD

**Issue by mgax** [CRJI/theblacksea.eu#40]
Articles:

* [x]  Match remaining old and new URLs (#51)
* [ ] assign missing images ~~(but wait for #54)~~
* [ ] clean up the intro text (e.g. look for html artifacts and CSS: http://wagtail.theblacksea.eu/stories/football-leaks-mesut-o-zil-in-spanish-tax-authority-probe/)
* [ ] check authors ~~(wait for #62)~~
* [ ] assign hero image (they are already imported in $54)
* [ ] check publishing date (some were parsed incorrectly) (see ~~#68~~)

---

Authors:

* [ ] correct names (diacritics, spelling) where needed (e.g. BLAŽ ZGAGA)

**Comment by mrc-toader** [comment]
@nightsh you also said something about meta content and/or other things I should walk him through?

**Comment by nightsh** [comment]
I updated the task description

**Comment by mgax** [comment]
Removing titles cleanup, I will script that: https://github.com/CRJI/theblacksea.eu/issues/39

**Comment by nightsh** [comment]
Images import in progress via script / management command in #54
